FROM golang:1.24-alpine

WORKDIR /service_stats_queue_worker

COPY . .

RUN go mod tidy
RUN go mod download
RUN go build -o service_stats_queue_worker ./project_executors/queue_worker

CMD ["./service_stats_queue_worker"]