FROM golang:1.24-alpine AS builder

ENV CGO_ENABLED=0

WORKDIR /app

RUN apk add --no-cache git

RUN go install github.com/hibiken/asynqmon/cmd/asynqmon@latest

FROM alpine:latest

RUN apk add --no-cache ca-certificates && \
    addgroup -S appgroup && adduser -S appuser -G appgroup

WORKDIR /app

COPY --from=builder /go/bin/asynqmon /usr/local/bin/asynqmon

USER appuser

EXPOSE 2222

CMD ["asynqmon", "-port=2222", "-redis-addr=redis:6379", "-enable-metrics-exporter"]
