FROM golang:1.24 as builder

WORKDIR /app

RUN go install github.com/hibiken/asynqmon/cmd/asynqmon@latest

FROM ubuntu:22.04

RUN apt-get update && apt-get install -y ca-certificates && rm -rf /var/lib/apt/lists/*

COPY --from=builder /go/bin/asynqmon /usr/local/bin/asynqmon

EXPOSE 2222

CMD ["asynqmon", "-port=2222", "-redis-addr=redis:6379", "-enable-metrics-exporter"]

