apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-stats
  labels:
    app: api-stats
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-stats
  template:
    metadata:
      labels:
        app: api-stats
    spec:
      containers:
        - name: api-stats
          image: us-central1-docker.pkg.dev/crypto-isotope-463815-t0/docker-repository/api-stats:v1
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          env:
            - name: SERVICE_STATS_POSTGRES_URL
              value: "host=postgres-service port=5432 user=stats_user password=stats_user_pass dbname=stats_db sslmode=disable"
            - name: NEW_RELIC_LICENSE_KEY
              value: "660128f2db4928bcddbbd4976fd21768FFFFNRAL"
            - name: NEW_RELIC_APP_NAME
              value: "service_stats"
            - name: ASYNC_QUEUE_HOST
              value: "redis"
            - name: ASYNC_QUEUE_PORT
              value: "6379"
