apiVersion: apps/v1
kind: Deployment
metadata:
  name: stats-worker
  labels:
    app: stats-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stats-worker
  template:
    metadata:
      labels:
        app: stats-worker
    spec:
      containers:
      - name: worker
        image: us-central1-docker.pkg.dev/crypto-isotope-463815-t0/docker-repository/stats-worker:latest
        imagePullPolicy: Always
        env:
        - name: SERVICE_STATS_POSTGRES_URL
          value: "host=postgres-service port=5432 user=stats_user password=stats_user_pass dbname=stats_db sslmode=disable"
        - name: ASYNC_QUEUE_HOST
          value: "redis.default.svc.cluster.local"
        - name: ASYNC_QUEUE_PORT
          value: "6379"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"