name: Deploy Stats Stack to GKE

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  GCP_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
  GCP_REGION: us-central1
  ARTIFACT_REGISTRY: ${{ secrets.ARTIFACT_REGISTRY }}
  CLUSTER_NAME: ${{ secrets.GKE_CLUSTER }}
  IMAGE_TAG: ${{ github.sha }}

jobs:
  setup-build-push-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    - name: Set up gcloud CLI
      uses: google-github-actions/setup-gcloud@v1

    - name: Configure Docker
      run: |
        gcloud auth configure-docker ${GCP_REGION}-docker.pkg.dev

    - name: Build and push images
      run: |
        # Construir y subir solo la imagen del worker desde Dockerfile.queue_worker
        docker build -t ${GCP_REGION}-docker.pkg.dev/$GCP_PROJECT/docker-repository/stats-worker:$IMAGE_TAG -f Dockerfile.queue_worker .
        docker push ${GCP_REGION}-docker.pkg.dev/$GCP_PROJECT/docker-repository/stats-worker:$IMAGE_TAG

        # Construir y subir la imagen de la API
        docker build -t ${GCP_REGION}-docker.pkg.dev/$GCP_PROJECT/docker-repository/api-stats:$IMAGE_TAG -f Dockerfile.api .
        docker push ${GCP_REGION}-docker.pkg.dev/$GCP_PROJECT/docker-repository/api-stats:$IMAGE_TAG

        # Construir y subir la imagen de Asynqmon (si es necesaria)
        docker build -t ${GCP_REGION}-docker.pkg.dev/$GCP_PROJECT/docker-repository/asynqmon:$IMAGE_TAG -f Dockerfile.asynqmon .
        docker push ${GCP_REGION}-docker.pkg.dev/$GCP_PROJECT/docker-repository/asynqmon:$IMAGE_TAG

    - name: Deploy to GKE
      run: |
        gcloud container clusters get-credentials ${CLUSTER_NAME} --region ${GCP_REGION}

        # Actualizar las imágenes en los manifests
        sed -i "s|us-central1-docker.pkg.dev/crypto-isotope-463815-t0/docker-repository/stats-worker:latest|${GCP_REGION}-docker.pkg.dev/${GCP_PROJECT}/docker-repository/stats-worker:${IMAGE_TAG}|g" k8s/worker-deployment.yaml
        sed -i "s|us-central1-docker.pkg.dev/crypto-isotope-463815-t0/docker-repository/api-stats:v1|${GCP_REGION}-docker.pkg.dev/${GCP_PROJECT}/docker-repository/api-stats:${IMAGE_TAG}|g" k8s/deployment.yaml

        kubectl apply -f k8s/
        kubectl wait --for=condition=available --timeout=300s deployment/stats-worker