name: Deploy Stats Service on GKE

on:
  push:
    branches:
      - main

jobs:
  deploy:
    uses: 1c2025-IngSoftware2-g7/ci_templates/.github/workflows/deploy-gke.yml@main
    with:
      service-name: api-stats
      docker-context: .
      docker-tag: v1
      k8s-path: k8s
    secrets:
      GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GKE_CLUSTER: ${{ secrets.GKE_CLUSTER }}
      GKE_ZONE: ${{ secrets.GKE_ZONE }}