name: Deploy Stats Stack to GKE

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  GCP_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
  GCP_REGION: us-central1
  ARTIFACT_REGISTRY: ${{ secrets.ARTIFACT_REGISTRY }}
  CLUSTER_NAME: ${{ secrets.GKE_CLUSTER }}
  IMAGE_TAG: ${{ github.sha }}

jobs:
  setup-build-push-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    - name: Set up gcloud CLI
      uses: google-github-actions/setup-gcloud@v1

    - name: Configure Docker
      run: |
        gcloud auth configure-docker ${GCP_REGION}-docker.pkg.dev

    - name: Build and push images
      run: |
        docker build -t us-central1-docker.pkg.dev/$GCP_PROJECT/docker-repository/stats-worker:$IMAGE_TAG -f Dockerfile.queue_worker .
    
        docker compose -f docker-compose.yml build
        
        docker images
        
        STATS_IMAGE="us-central1-docker.pkg.dev/$GCP_PROJECT/docker-repository/api-stats:$IMAGE_TAG"
        WORKER_IMAGE="us-central1-docker.pkg.dev/$GCP_PROJECT/docker-repository/stats-worker:$IMAGE_TAG"
        ASYNQMON_IMAGE="us-central1-docker.pkg.dev/$GCP_PROJECT/docker-repository/asynqmon:$IMAGE_TAG"
        
        docker tag service_stats-service_stats "$STATS_IMAGE"
        docker tag service_stats-service_stats_queue_worker "$WORKER_IMAGE"
        docker tag service_stats-asynqmon "$ASYNQMON_IMAGE"
        
        docker push "$STATS_IMAGE"
        docker push "$WORKER_IMAGE"
        docker push "$ASYNQMON_IMAGE"

    - name: Deploy to GKE
      run: |
        echo "Instalando gke-gcloud-auth-plugin..."
        sudo apt-get update
        sudo apt-get install -y apt-transport-https ca-certificates gnupg
        echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
        curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
        sudo apt-get update && sudo apt-get install -y google-cloud-sdk-gke-gcloud-auth-plugin

        echo "Configurando acceso al cluster..."
        gcloud container clusters get-credentials ${CLUSTER_NAME} --region ${GCP_REGION}

        echo "Actualizando manifests..."
        [ -f "k8s/deployment.yaml" ] && sed -i "s|us-central1-docker.pkg.dev/crypto-isotope-463815-t0/docker-repository/api-stats:v1|${GCP_REGION}-docker.pkg.dev/${GCP_PROJECT}/docker-repository/api-stats:${IMAGE_TAG}|g" k8s/deployment.yaml
        [ -f "k8s/worker-deployment.yaml" ] && sed -i "s|us-central1-docker.pkg.dev/crypto-isotope-463815-t0/docker-repository/api-stats:v1|${GCP_REGION}-docker.pkg.dev/${GCP_PROJECT}/docker-repository/stats-worker:${IMAGE_TAG}|g" k8s/worker-deployment.yaml

        echo "Aplicando configuración en GKE..."
        kubectl apply -f k8s/

        echo "Esperando que los deployments estén listos..."
        kubectl wait --for=condition=available --timeout=300s deployment/api-stats || echo "Deployment api-stats no encontrado"
        kubectl wait --for=condition=available --timeout=300s deployment/stats-worker || echo "Deployment stats-worker no encontrado"
    
    - name: Verify deployment
      run: |
        kubectl get pods
        kubectl get services
