name: Deploy Stats Stack to GKE

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  GCP_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
  GCP_REGION: us-central1
  ARTIFACT_REGISTRY: ${{ secrets.ARTIFACT_REGISTRY }}
  CLUSTER_NAME: ${{ secrets.GKE_CLUSTER }}
  IMAGE_TAG: ${{ github.sha }}

jobs:
  setup-build-push-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    - name: Set up gcloud CLI
      uses: google-github-actions/setup-gcloud@v1

    - name: Configure Docker
      run: |
        gcloud auth configure-docker ${GCP_REGION}-docker.pkg.dev

    - name: Build and push images
      run: |
        docker compose -f docker-compose.yml build
        
        docker images
        
        STATS_IMAGE="us-central1-docker.pkg.dev/$GCP_PROJECT/docker-repository/api-stats:$IMAGE_TAG"
        WORKER_IMAGE="us-central1-docker.pkg.dev/$GCP_PROJECT/docker-repository/stats-worker:$IMAGE_TAG"
        ASYNQMON_IMAGE="us-central1-docker.pkg.dev/$GCP_PROJECT/docker-repository/asynqmon:$IMAGE_TAG"
        
        docker tag service_stats-service_stats "$STATS_IMAGE"
        docker tag service_stats-service_stats_queue_worker "$WORKER_IMAGE"
        docker tag service_stats-asynqmon "$ASYNQMON_IMAGE"
        
        docker push "$STATS_IMAGE"
        docker push "$WORKER_IMAGE"
        docker push "$ASYNQMON_IMAGE"

    - name: Deploy to GKE
      run: |
        sudo apt-get update && sudo apt-get install google-cloud-sdk-gke-gcloud-auth-plugin -y
        gcloud components install gke-gcloud-auth-plugin
        
        gcloud container clusters get-credentials ${CLUSTER_NAME} --region ${GCP_REGION}
        
        if [ ! -f "k8s/worker-deployment.yaml" ]; then
          echo "⚠️ Advertencia: worker-deployment.yaml no existe, continuando sin él"
        fi
        
        [ -f "k8s/deployment.yaml" ] && sed -i "s|us-central1-docker.pkg.dev/crypto-isotope-463815-t0/docker-repository/api-stats:v1|${GCP_REGION}-docker.pkg.dev/${GCP_PROJECT}/docker-repository/api-stats:${IMAGE_TAG}|g" k8s/deployment.yaml
        [ -f "k8s/worker-deployment.yaml" ] && sed -i "s|us-central1-docker.pkg.dev/crypto-isotope-463815-t0/docker-repository/api-stats:v1|${GCP_REGION}-docker.pkg.dev/${GCP_PROJECT}/docker-repository/stats-worker:${IMAGE_TAG}|g" k8s/worker-deployment.yaml
        
        kubectl apply -f k8s/
        
        kubectl wait --for=condition=available --timeout=300s deployment/api-stats || true
        kubectl wait --for=condition=available --timeout=300s deployment/stats-worker || true

    - name: Verify deployment
      run: |
        kubectl get pods
        kubectl get services